;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Gameplay.Event.Montage.Player.Kick",NewTagName="Gameplay.Event.Montage.Player.SwordAttack")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Gameplay.Ability.Player.Heal",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Player.PunchAttack",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Player.ShieldDefend",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Player.SwordAttack",DevComment="")
+GameplayTagList=(Tag="Gameplay.Event.Montage.Player.Punch",DevComment="")
+GameplayTagList=(Tag="Gameplay.Event.Montage.Player.ShieldDefend",DevComment="")
+GameplayTagList=(Tag="Gameplay.Event.Montage.Player.SwordAttack",DevComment="")
+GameplayTagList=(Tag="Gameplay.Magnitude.Duration",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Player.IsHealing",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Player.IsPunchAttacking",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Player.IsShieldDefending",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.Player.IsSwordAttacking",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Player.Attack",DevComment="")

